### ISSUE TITLE
Please stop using my Google Maps API

### ISSUE THREAD

**Issue by MrRetail** [mukundsrinath/Privacy-Date-Extraction-DocEng#1]
Sorry for contacting you here but there doesn't appear to be any way to contact Github users other than raising an "issue". Google has sent me a warning, saying that you have publicly posted a Google Maps API that I created when I used to have a free developers account. Please email me at info@digitalmanaged.com so I can tell you which API it is. If I tell you here, then I am simply publicly posting it again. I really need you to take it down please. It was posted on something called "CoLiPPS/blob/" I believe.
Thank you,
Bryan

**Comment by mukundsrinath** [comment]
I have taken down the repo CoLiPPs. Apologies for the inconvenience.

**Comment by MrRetail** [comment]
Thank you, much appreciated.
